version: '3.8'

services:
  russian-helloworld:
    container_name: russian-helloworld
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/usr/src
    tty: true
    ports:
      - 4321:4321